@startuml io

  node "External container" as external_container {
    interface "tcp/ip" as external_tcp_ip
    node "External process (V8 support)" as external_process {
      interface "ws+http" as external_websocket
      node "Main thread" as external_main_thread {
        component ExternalNode
      }
      ExternalNode --( external_websocket
    }
    external_websocket --( external_tcp_ip
  }

  node "Internal container" as internal_container {
    interface "tcp/ip" as internal_tcp_ip
    node "Internal process (V8 support)" as internal_process {
      interface "ws+http" as internal_websocket
      node "Main thread" as internal_main_thread {
        component InternalNode
      }
      InternalNode --( internal_websocket
      internal_websocket --( internal_tcp_ip
    }
  }

  cloud "Network" as network
  external_tcp_ip -- network
  internal_tcp_ip -- network 

  node "Router container" as router_container {
    interface "tcp/ip" as router_tcp_ip

    node "Router process (V8 support)" as router_process {
      interface "ws+http" as router_websocket

      node "Main thread" as router_main_thread {
        component Router
        component NodesList
        component ResourcesList
        component RoutersList
        Router *- NodesList
        ResourcesList -* Router
        Router *-- RoutersList
      }
    }
    network -- router_tcp_ip
    router_tcp_ip )-- router_websocket
    router_websocket )-- Router
  }
@enduml
